In [56]:
import pandas as pd
df=pd.read_csv(r"C:\Users\user\Titanic-Dataset.csv")

In [59]:
df.describe()

,Age,SibSp,Parch,Fare,PassengerId,Pclass,Survived
count,714.000000,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000
mean,29.699118,0.523008,0.381594,32.204208,446.000000,2.308642,0.383838
std,14.526497,1.102743,0.806057,49.693429,257.353842,0.836071,0.486592
min,0.420000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000
25%,20.125000,0.000000,0.000000,7.910400,223.500000,2.000000,0.000000
50%,28.000000,0.000000,0.000000,14.454200,446.000000,3.000000,0.000000
75%,38.000000,1.000000,0.000000,31.000000,668.500000,3.000000,1.000000
max,80.000000,8.000000,6.000000,512.329200,891.000000,3.000000,1.000000

In [57]:
df.head()
df.tail()

,Name,Sex,Age,SibSp,Parch,Embarked,Ticket,Fare,Cabin,PassengerId,Pclass,Survived
886,"Montvila, Rev. Juozas",male,27.0,0,0,S,211536,13.00,NaN,887,2,0
887,"Graham, Miss. Margaret Edith",female,19.0,0,0,S,112053,30.00,B42,888,1,1
888,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,S,W./C. 6607,23.45,NaN,889,3,0
889,"Behr, Mr. Karl Howell",male,26.0,0,0,C,111369,30.00,C148,890,1,1
890,"Dooley, Mr. Patrick",male,32.0,0,0,Q,370376,7.75,NaN,891,3,0

In [58]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         891 non-null    str
 1   Sex          891 non-null    str
 2   Age          714 non-null    float64
 3   SibSp        891 non-null    int64
 4   Parch        891 non-null    int64
 5   Embarked     889 non-null    str
 6   Ticket       891 non-null    str
 7   Fare         891 non-null    float64
 8   Cabin        204 non-null    str
 9   PassengerId  891 non-null    int64
 10  Pclass       891 non-null    int64
 11  Survived     891 non-null    int64
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [54]:
df.columns

Index(['Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Embarked', 'Ticket', 'Fare',
       'Cabin', 'PassengerId', 'Pclass', 'Survived'],
      dtype='str')

In [61]:
print(df.shape)
print(df["Age"].mean())
print(df["Age"].mode())
print(df["Age"].median())
print(df["Age"].var())
print(df["Age"].std())
print(df["Age"].min())
print(df["Age"].max())
print(df["Age"].count())
print(df["Age"].unique())

(891, 12)
29.69911764705882
0    24.0
Name: Age, dtype: float64
28.0
211.01912474630802
14.526497332334042
0.42
80.0
714
[22.   38.   26.   35.     nan 54.    2.   27.   14.    4.   58.   20.
 39.   55.   31.   34.   15.   28.    8.   19.   40.   66.   42.   21.
 18.    3.    7.   49.   29.   65.   28.5   5.   11.   45.   17.   32.
 16.   25.    0.83 30.   33.   23.   24.   46.   59.   71.   37.   47.
 14.5  70.5  32.5  12.    9.   36.5  51.   55.5  40.5  44.    1.   61.
 56.   50.   36.   45.5  20.5  62.   41.   52.   63.   23.5   0.92 43.
 60.   10.   64.   13.   48.    0.75 53.   57.   80.   70.   24.5   6.
  0.67 30.5   0.42 34.5  74.  ]

In [62]:
df["Age"].nunique()

88

In [63]:
df["Age"].value_counts()

Age
24.00    30
22.00    27
18.00    26
28.00    25
19.00    25
         ..
24.50     1
0.67      1
0.42      1
34.50     1
74.00     1
Name: count, Length: 88, dtype: int64

In [55]:
df.dropna()

,Name,Sex,Age,SibSp,Parch,Embarked,Ticket,Fare,Cabin,PassengerId,Pclass,Survived
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,C,PC 17599,71.2833,C85,2,1,1
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,S,113803,53.1000,C123,4,1,1
6,"McCarthy, Mr. Timothy J",male,54.0,0,0,S,17463,51.8625,E46,7,1,0
10,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,S,PP 9549,16.7000,G6,11,3,1
11,"Bonnell, Miss. Elizabeth",female,58.0,0,0,S,113783,26.5500,C103,12,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...
871,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,S,11751,52.5542,D35,872,1,1
872,"Carlsson, Mr. Frans Olof",male,33.0,0,0,S,695,5.0000,B51 B53 B55,873,1,0
879,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,C,11767,83.1583,C50,880,1,1
887,"Graham, Miss. Margaret Edith",female,19.0,0,0,S,112053,30.0000,B42,888,1,1
889,"Behr, Mr. Karl Howell",male,26.0,0,0,C,111369,30.0000,C148,890,1,1

In [64]:
df.isnull()

,Name,Sex,Age,SibSp,Parch,Embarked,Ticket,Fare,Cabin,PassengerId,Pclass,Survived
0,False,False,False,False,False,False,False,False,True,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,True,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
886,False,False,False,False,False,False,False,False,True,False,False,False
887,False,False,False,False,False,False,False,False,False,False,False,False
888,False,False,True,False,False,False,False,False,True,False,False,False
889,False,False,False,False,False,False,False,False,False,False,False,False
890,False,False,False,False,False,False,False,False,True,False,False,False

In [65]:
df.isnull().sum()

Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Embarked         2
Ticket           0
Fare             0
Cabin          687
PassengerId      0
Pclass           0
Survived         0
dtype: int64

In [66]:
df.isnull().mean()*100

Name            0.000000
Sex             0.000000
Age            19.865320
SibSp           0.000000
Parch           0.000000
Embarked        0.224467
Ticket          0.000000
Fare            0.000000
Cabin          77.104377
PassengerId     0.000000
Pclass          0.000000
Survived        0.000000
dtype: float64

In [52]:
df.fillna(0)

,Name,Sex,Age,SibSp,Parch,Embarked,Ticket,Fare,Cabin,PassengerId,Pclass,Survived
0,"Braund, Mr. Owen Harris",male,22.0,1,0,S,A/5 21171,7.2500,0,1,3,0
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,C,PC 17599,71.2833,C85,2,1,1
2,"Heikkinen, Miss. Laina",female,26.0,0,0,S,STON/O2. 3101282,7.9250,0,3,3,1
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,S,113803,53.1000,C123,4,1,1
4,"Allen, Mr. William Henry",male,35.0,0,0,S,373450,8.0500,0,5,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...
886,"Montvila, Rev. Juozas",male,27.0,0,0,S,211536,13.0000,0,887,2,0
887,"Graham, Miss. Margaret Edith",female,19.0,0,0,S,112053,30.0000,B42,888,1,1
888,"Johnston, Miss. Catherine Helen ""Carrie""",female,0.0,1,2,S,W./C. 6607,23.4500,0,889,3,0
889,"Behr, Mr. Karl Howell",male,26.0,0,0,C,111369,30.0000,C148,890,1,1
890,"Dooley, Mr. Patrick",male,32.0,0,0,Q,370376,7.7500,0,891,3,0

In [43]:
(df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
886    False
887    False
888    False
889    False
890    False
Length: 891, dtype: bool

In [51]:
df[["Age","Fare"]]

      Age     Fare
0    22.0   7.2500
1    38.0  71.2833
2    26.0   7.9250
3    35.0  53.1000
4    35.0   8.0500
..    ...      ...
886  27.0  13.0000
887  19.0  30.0000
888   NaN  23.4500
889  26.0  30.0000
890  32.0   7.7500

[891 rows x 2 columns]

In [49]:
df.iloc[0:5]

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0

   Parch Embarked            Ticket     Fare Cabin  PassengerId  Pclass  \
0      0        S         A/5 21171   7.2500   NaN            1       3
1      0        C          PC 17599  71.2833   C85            2       1
2      0        S  STON/O2. 3101282   7.9250   NaN            3       3
3      0        S            113803  53.1000  C123            4       1
4      0        S            373450   8.0500   NaN            5       3

   Survived
0         0
1         1
2         1
3         1
4         0

In [50]:
df[df["Age"]>50]

,Name,Sex,Age,SibSp,Parch,Embarked,Ticket,Fare,Cabin,PassengerId,Pclass,Survived
6,"McCarthy, Mr. Timothy J",male,54.0,0,0,S,17463,51.8625,E46,7,1,0
11,"Bonnell, Miss. Elizabeth",female,58.0,0,0,S,113783,26.5500,C103,12,1,1
15,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,S,248706,16.0000,NaN,16,2,1
33,"Wheadon, Mr. Edward H",male,66.0,0,0,S,C.A. 24579,10.5000,NaN,34,2,0
54,"Ostby, Mr. Engelhart Cornelius",male,65.0,0,1,C,113509,61.9792,B30,55,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
820,"Hays, Mrs. Charles Melville (Clara Jennings Gr...",female,52.0,1,1,S,12749,93.5000,B69,821,1,1
829,"Stone, Mrs. George Nelson (Martha Evelyn)",female,62.0,0,0,NaN,113572,80.0000,B28,830,1,1
851,"Svensson, Mr. Johan",male,74.0,0,0,S,347060,7.7750,NaN,852,3,0
857,"Daly, Mr. Peter Denis",male,51.0,0,0,S,113055,26.5500,E17,858,1,1
879,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,C,11767,83.1583,C50,880,1,1

In [53]:
df.sort_values("Fare")

,Name,Sex,Age,SibSp,Parch,Embarked,Ticket,Fare,Cabin,PassengerId,Pclass,Survived
815,"Fry, Mr. Richard",male,NaN,0,0,S,112058,0.0000,B102,816,1,0
806,"Andrews, Mr. Thomas Jr",male,39.0,0,0,S,112050,0.0000,A36,807,1,0
413,"Cunningham, Mr. Alfred Fleming",male,NaN,0,0,S,239853,0.0000,NaN,414,2,0
481,"Frost, Mr. Anthony Wood ""Archie""",male,NaN,0,0,S,239854,0.0000,NaN,482,2,0
302,"Johnson, Mr. William Cahoone Jr",male,19.0,0,0,S,LINE,0.0000,NaN,303,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...
438,"Fortune, Mr. Mark",male,64.0,1,4,S,19950,263.0000,C23 C25 C27,439,1,0
341,"Fortune, Miss. Alice Elizabeth",female,24.0,3,2,S,19950,263.0000,C23 C25 C27,342,1,1
737,"Lesurer, Mr. Gustave J",male,35.0,0,0,C,PC 17755,512.3292,B101,738,1,1
679,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,C,PC 17755,512.3292,B51 B53 B55,680,1,1
258,"Ward, Miss. Anna",female,35.0,0,0,C,PC 17755,512.3292,NaN,259,1,1

In [67]:
df.rename(columns={"Fare":"ticket_prize"})

,Name,Sex,Age,SibSp,Parch,Embarked,Ticket,ticket_prize,Cabin,PassengerId,Pclass,Survived
0,"Braund, Mr. Owen Harris",male,22.0,1,0,S,A/5 21171,7.2500,NaN,1,3,0
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,C,PC 17599,71.2833,C85,2,1,1
2,"Heikkinen, Miss. Laina",female,26.0,0,0,S,STON/O2. 3101282,7.9250,NaN,3,3,1
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,S,113803,53.1000,C123,4,1,1
4,"Allen, Mr. William Henry",male,35.0,0,0,S,373450,8.0500,NaN,5,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...
886,"Montvila, Rev. Juozas",male,27.0,0,0,S,211536,13.0000,NaN,887,2,0
887,"Graham, Miss. Margaret Edith",female,19.0,0,0,S,112053,30.0000,B42,888,1,1
888,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,S,W./C. 6607,23.4500,NaN,889,3,0
889,"Behr, Mr. Karl Howell",male,26.0,0,0,C,111369,30.0000,C148,890,1,1
890,"Dooley, Mr. Patrick",male,32.0,0,0,Q,370376,7.7500,NaN,891,3,0

In [68]:
df.drop("Parch",axis=1)

,Name,Sex,Age,SibSp,Embarked,Ticket,Fare,Cabin,PassengerId,Pclass,Survived
0,"Braund, Mr. Owen Harris",male,22.0,1,S,A/5 21171,7.2500,NaN,1,3,0
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,C,PC 17599,71.2833,C85,2,1,1
2,"Heikkinen, Miss. Laina",female,26.0,0,S,STON/O2. 3101282,7.9250,NaN,3,3,1
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,S,113803,53.1000,C123,4,1,1
4,"Allen, Mr. William Henry",male,35.0,0,S,373450,8.0500,NaN,5,3,0
...,...,...,...,...,...,...,...,...,...,...,...
886,"Montvila, Rev. Juozas",male,27.0,0,S,211536,13.0000,NaN,887,2,0
887,"Graham, Miss. Margaret Edith",female,19.0,0,S,112053,30.0000,B42,888,1,1
888,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,S,W./C. 6607,23.4500,NaN,889,3,0
889,"Behr, Mr. Karl Howell",male,26.0,0,C,111369,30.0000,C148,890,1,1
890,"Dooley, Mr. Patrick",male,32.0,0,Q,370376,7.7500,NaN,891,3,0

In [74]:
df.groupby("Fare")